ntp_servers:
- 0.north-america.pool.ntp.org
- 1.north-america.pool.ntp.org

dns_servers:
- 1.1.1.1

compliance_hipaa_ntp_servers:
- 2.north-america.pool.ntp.org
- 3.north-america.pool.ntp.org

compliance_hipaa_dns_servers:
- 8.8.8.8

log_host: 10.1.150.1

psns:
  - name: US_EAST_PSN1
    address: 1.1.1.1
  - name: US_EAST_PSN2
    address: 1.1.1.2
  - name: US_WEST_PSN1
    address: 1.1.1.3
psn_key: test123


